apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "prod"
          image: lutogin/auth:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 3000
              path: /health
            periodSeconds: 5
            initialDelaySeconds: 5