apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "prod"
            - name: AUTH_HOST
              value: "auth-service.default:3000"
            - name: TASKS_HOST
              value: "tasks-service.default:3000"
          image: lutogin/core:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 3000
              path: /health
            periodSeconds: 5
            initialDelaySeconds: 5