apiVersion: apps/v1
kind: Deployment

metadata:
  name: nest-deployment
  labels:
    app: nest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-app
#      tier: backend
  template:
    metadata:
      labels:
        app: nest-app
#        tier: backend
    spec:
      containers:
        - name: nest-node
          image: lutogin/nest
#        - name: nest-node
#          image: lutogin/nest