apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: prod
          image: lutogin/tasks:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 3000
              path: /health
            periodSeconds: 5
            initialDelaySeconds: 5